version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    volumes:
      - .:/app
      - /app/node_modules # ⚠️ Prevents overriding node_modules
    environment:
      NODE_ENV: production
